# ================================
# ZAIRAKAI DOCKER ECOSYSTEM
# Docker Swarm Stack - Laravel + Vue.js
# ================================
# Production-ready high-availability deployment
#
# Deploy:
#   docker stack deploy -c stack-laravel.yml myapp
#
# Update:
#   docker service update --image registry.gitlab.com/zairakai/docker-ecosystem/php:8.3-prod myapp_php
#
# Scale:
#   docker service scale myapp_php=10 myapp_node=5

services:
  # ================================
  # PHP (Laravel Backend)
  # ================================
  php:
    image: registry.gitlab.com/zairakai/docker-ecosystem/php:8.3-prod
    networks:
      - backend
      - frontend
    environment:
      APP_NAME: "Laravel App"
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: https://app.example.com
      LOG_CHANNEL: json
      LOG_LEVEL: warning

      # Database
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: app
      DB_USERNAME: app_user

      # Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379

      # Cache
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_CONNECTION: redis

    secrets:
      - db_password
      - app_key
      - jwt_secret

    deploy:
      mode: replicated
      replicas: 5
      update_config:
        parallelism: 2
        delay: 10s
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
      placement:
        max_replicas_per_node: 2
        constraints:
          - node.role == worker
      labels:
        com.zairakai.service: "php"
        com.zairakai.stack: "laravel"

    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # ================================
  # Node.js (Vue Frontend)
  # ================================
  node:
    image: registry.gitlab.com/zairakai/docker-ecosystem/node:20-prod
    networks:
      - frontend
    environment:
      NODE_ENV: production
      API_URL: "http://php:9000"
      REDIS_HOST: redis
      REDIS_PORT: 6379

    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
      placement:
        constraints:
          - node.role == worker
      labels:
        com.zairakai.service: "node"
        com.zairakai.stack: "laravel"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # ================================
  # Nginx (Web Server / Load Balancer)
  # ================================
  nginx:
    image: registry.gitlab.com/zairakai/docker-ecosystem/web:nginx-1.26
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    networks:
      - frontend
    configs:
      - source: nginx_config
        target: /etc/nginx/conf.d/default.conf

    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.25"
          memory: 128M
        reservations:
          cpus: "0.1"
          memory: 64M
      placement:
        constraints:
          - node.role == worker
      labels:
        com.zairakai.service: "nginx"
        com.zairakai.stack: "laravel"

  # ================================
  # MySQL Database (with replication)
  # ================================
  mysql:
    image: registry.gitlab.com/zairakai/docker-ecosystem/database:mysql-8.0
    networks:
      - backend
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app_user
    secrets:
      - mysql_root_password
      - mysql_password
    volumes:
      - mysql_data:/var/lib/mysql

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.database == true
      restart_policy:
        condition: on-failure
        delay: 10s
      resources:
        limits:
          cpus: "2.0"
          memory: 2G
        reservations:
          cpus: "0.5"
          memory: 1G
      labels:
        com.zairakai.service: "mysql"
        com.zairakai.stack: "laravel"

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: MySQL Replica (read-only)
  mysql-replica:
    image: registry.gitlab.com/zairakai/docker-ecosystem/database:mysql-8.0
    networks:
      - backend
    environment:
      MYSQL_REPLICATION_MODE: slave
      MYSQL_MASTER_HOST: mysql
      MYSQL_MASTER_PORT: 3306
      MYSQL_DATABASE: app
      MYSQL_USER: app_user
    secrets:
      - mysql_root_password
      - mysql_password
    volumes:
      - mysql_replica_data:/var/lib/mysql

    deploy:
      mode: replicated
      replicas: 0 # Set to 1+ to enable replication
      placement:
        constraints:
          - node.labels.database == true
          - node.hostname != mysql
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "2.0"
          memory: 2G
        reservations:
          cpus: "0.5"
          memory: 1G
      labels:
        com.zairakai.service: "mysql-replica"
        com.zairakai.stack: "laravel"

  # ================================
  # Redis Cache (with Sentinel)
  # ================================
  redis:
    image: registry.gitlab.com/zairakai/docker-ecosystem/database:redis-7
    networks:
      - backend
      - frontend
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    secrets:
      - redis_password
    volumes:
      - redis_data:/data

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.1"
          memory: 256M
      labels:
        com.zairakai.service: "redis"
        com.zairakai.stack: "laravel"

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Redis Sentinel (for HA)
  redis-sentinel:
    image: redis:7-alpine
    networks:
      - backend
    command: redis-sentinel /etc/redis/sentinel.conf
    configs:
      - source: redis_sentinel_config
        target: /etc/redis/sentinel.conf

    deploy:
      mode: replicated
      replicas: 0 # Set to 3 to enable Sentinel
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.25"
          memory: 128M
      labels:
        com.zairakai.service: "redis-sentinel"
        com.zairakai.stack: "laravel"

# ================================
# NETWORKS
# ================================
networks:
  frontend:
    driver: overlay
    attachable: true
    driver_opts:
      encrypted: "true"

  backend:
    driver: overlay
    attachable: false
    driver_opts:
      encrypted: "true"

# ================================
# VOLUMES
# ================================
volumes:
  mysql_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/data/mysql

  mysql_replica_data:
    driver: local

  redis_data:
    driver: local

# ================================
# SECRETS
# ================================
# Create secrets before deploying:
#   echo "password" | docker secret create db_password -
#   echo "base64:…" | docker secret create app_key -
#   echo "secret" | docker secret create jwt_secret -
#   echo "root_password" | docker secret create mysql_root_password -
#   echo "user_password" | docker secret create mysql_password -
#   echo "redis_password" | docker secret create redis_password -

secrets:
  db_password:
    external: true

  app_key:
    external: true

  jwt_secret:
    external: true

  mysql_root_password:
    external: true

  mysql_password:
    external: true

  redis_password:
    external: true

# ================================
# CONFIGS
# ================================
configs:
  nginx_config:
    external: true

  redis_sentinel_config:
    external: true
