FROM mailhog/mailhog:v1.0.1

LABEL maintainer="Stanislas Poisson <stanislas.p@the-white-rabbits.com>"
LABEL version="mailhog"
LABEL description="MailHog SMTP testing server for development (wrapper)"
