# ================================
# API ONLY SETUP
# ================================
# Laravel API backend without frontend
# Perfect for mobile app backends or microservices

services:
  # Laravel API
  api:
    image: registry.gitlab.com/zairakai/docker-ecosystem/php:8.3-prod
    container_name: laravel-api
    volumes:
      - ./:/var/www/html:ro
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - API_ONLY=true
    depends_on:
      - mysql
      - redis
    restart: unless-stopped
    networks:
      - api-network

  # Nginx API Gateway
  nginx:
    image: registry.gitlab.com/zairakai/docker-ecosystem/web:nginx-1.26
    container_name: api-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/api.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/ssl/certs:ro
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - api-network

  # MySQL Database
  mysql:
    image: registry.gitlab.com/zairakai/docker-ecosystem/database:mysql-8.0
    container_name: api-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - api-network

  # Redis Cache
  redis:
    image: registry.gitlab.com/zairakai/docker-ecosystem/database:redis-7
    container_name: api-redis
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - api-network

networks:
  api-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
