# ================================
# MINIMAL LARAVEL SETUP
# ================================
# Simple Laravel backend development environment
# Includes: PHP-dev, MySQL, Redis
#
# Images: Pulled from Docker Hub (zairakai/*)
# Alternative: Use GitLab Registry (registry.gitlab.com/zairakai/docker-ecosystem/*)
# See README.md for image naming conventions

services:
  # Laravel Application
  app:
    image: zairakai/php:8.3-dev
    container_name: laravel-app
    volumes:
      - ./:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - XDEBUG_MODE=develop,debug
    depends_on:
      - mysql
      - redis
    networks:
      - laravel-network

  # MySQL Database
  mysql:
    image: zairakai/mysql:8.0
    container_name: laravel-mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel-network

  # Redis Cache
  redis:
    image: zairakai/redis:7
    container_name: laravel-redis
    volumes:
      - redis_data:/data
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
