FROM minio/minio:RELEASE.2025-09-07T16-13-09Z

LABEL maintainer="Stanislas Poisson <stanislas.p@the-white-rabbits.com>"
LABEL version="minio"
LABEL description="MinIO S3-compatible object storage for development (wrapper)"
